---

- name: restart apache
  become: yes
  become_user: root
  service:
    name: apache2
    state: restarted

- name: restart mysql
  become: yes
  become_user: root
  service:
    name: mysql
    state: restarted

- name: clean-up mediawiki zip
  become: yes
  become_user: root
  file:
   path: "/tmp/mediawiki-1.32.1.tar.gz"
   state: absent

- name: clean-up sql.sh
  become: yes
  become_user: root
  file:
   path: "/tmp/sql.sh"
   state: absent
