---

- name: download mediawiki
  become: yes
  become_user: root
  get_url:
    url: https://releases.wikimedia.org/mediawiki/1.32/mediawiki-1.32.1.tar.gz
    dest: /tmp/mediawiki-1.32.1.tar.gz

- name: unzip mediawiki
  become: yes
  become_user: root
  unarchive:
    src: /tmp/mediawiki-1.32.1.tar.gz
    dest: /tmp
    remote_src: yes

- name: move mediawiki zip
  become: yes
  become_user: root
  shell: mv -u /tmp/mediawiki-1.32.1 /var/lib/mediawiki

- name: Create symbolic link
  become: yes
  become_user: root
  file:
   dest: "/var/www/html/mediawiki"
   src: "/var/lib/mediawiki"
   state: link
   force: yes


- name: enable php mods
  become: yes
  become_user: root
  shell: phpenmod mbstring && sudo phpenmod xml
  notify:
    - clean-up mediawiki zip
    - restart apache
